# frozen_string_literal: true

source "https://rubygems.org"

gem 'rexml'

gem 'rubyzip', '1.2.1'

gem 'kraken-mobile', path: '../../KrakenMobile-1.0.9'

#git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
